// Sidebar
const SIDEBAR_VISIBILITY_TOGGLE = 'SIDEBAR_VISIBILITY_TOGGLE';
const SIDEBAR_VISIBILITY_SHOW = 'SIDEBAR_VISIBILITY_SHOW';
const SIDEBAR_VISIBILITY_HIDE = 'SIDEBAR_VISIBILITY_HIDE';
/*export const SIDEBAR_STICKY_TOGGLE = 'SIDEBAR_STICKY_TOGGLE';
export const SIDEBAR_STICKY_ENABLE = 'SIDEBAR_STICKY_ENABLE';
export const SIDEBAR_STICKY_DISABLE = 'SIDEBAR_STICKY_DISABLE';
*/
// Layout
/*export const LAYOUT_BOXED_TOGGLE = 'LAYOUT_BOXED_TOGGLE';
export const LAYOUT_BOXED_ENABLE = 'LAYOUT_BOXED_ENABLE';
export const LAYOUT_BOXED_DISABLE = 'LAYOUT_BOXED_DISABLE';*/

// Theme
// export const THEME_TOGGLE = 'THEME_TOGGLE';

// Auth
const AUTH_SUCCESS = 'AUTH_SUCCESS';
const AUTH_CLEAR = 'AUTH_CLEAR';
const AUTH_SET_USER = 'AUTH_SET_USER';

// Common Actions
const LOAD_STATUS = 'LOAD_STATUS';
const SAVE_STATUS = 'SAVE_STATUS';
const SET_META = 'SET_META';
const SET_ITEMS = 'SET_ITEMS';
const SET_FILTERS = 'SET_FILTERS';

export {
	SIDEBAR_VISIBILITY_TOGGLE,
	SIDEBAR_VISIBILITY_SHOW,
	SIDEBAR_VISIBILITY_HIDE,
	AUTH_SUCCESS,
	AUTH_CLEAR,
	AUTH_SET_USER,
	LOAD_STATUS,
	SAVE_STATUS,
	SET_META,
	SET_ITEMS,
	SET_FILTERS
}
